steps:
- name: 'summoners orchestration'
  args:
  - gcloud
  - functions
  - deploy
  - orchestration
  - --region=us-central1
  - --source=.
  - --trigger-http
  - --runtime=python3.9
  options:
    secretEnv: Riot_API_Key