steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - summoners_orchestration
  - --region=us-central1
  - --source=./functions
  - --trigger-httpasdfa sdf adfasdf ad ffa f d
  - --allow-unauthenticated
  - --entry-point=entrypoint
  - --set-secrets=[Riot_API_Key=projects/451871121938/secrets/Riot_API_Keydasdf :latest]