steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - summoners_orchestration
  - --region=us-central1
  - --source=./functions
  - --trigger-http
  - --runtime=python39
  - --allow-unauthenticated
  - --entry-point=entrypoint
  - --set-secrets=[Riot_API_Key=Riot_API_Key:latest]